version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/bizloan
hooks:
  AfterInstall:
    - location: deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
