version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/bizloan
hooks:
  BeforeInstall:
    - location: deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy_scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/start_server.sh
    - location: deploy_scripts/create_test_db.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy_scripts/stop_server.sh
      timeout: 300
      runas: root
